### ISSUE TITLE
Errors when opening i-demo.otf + workarounds

### ISSUE THREAD

**Issue by louisremi** [rocallahan/svg-opentype-workshop#3]
When I open the i-demo.otf I get the following error message:

```
Invalid SVG: Parse error: XML Parsing Error: not well-formed Location: [masked] Line Number 1, Column 1:='http://www.w3.org/2000/svg'> ^
```

The content of the svg textarea begins as follows:

```
='http://www.w3.org/2000/svg'>
<g id='glyph76' fill="red">
...
```

I fixed this first error by inserting `<svg xmlns` right before the `=` and I got the following error:

```
Invalid SVG: Parse error: XML Parsing Error: not well-formed Location: [masked] Line Number 11, Column 7:</svg>
```

I had to delete several invisible characters after the closing `</svg>` to fix that one ; and after that the demo worked.

**Comment by rocallahan** [comment]
Fixed by commit 774dc328e5ccc6e207db8842930d1608436ff01f.
