### ISSUE TITLE
rename master branch to gh-pages

### ISSUE THREAD

**Issue by flying-sheep** [rocallahan/svg-opentype-workshop#5]
then this tool can be simply used by going to http://rocallahan.github.com/svg-opentype-workshop/

**Comment by miguelsousa** [comment]
@flying-sheep you can load the page this way http://htmlpreview.github.io/?https://github.com/rocallahan/svg-opentype-workshop/blob/master/index.html

**Comment by flying-sheep** [comment]
i know, but my option is simpler :)

**Comment by rocallahan** [comment]
It looks like I can't actually delete the master branch, but I've created the gh-pages branch.

**Comment by flying-sheep** [comment]
Thanks! I'm sure you can delete it, but it's probably not important.

**Comment by flying-sheep** [comment]
so what you’d do is 
1. go to the [project settings](https://github.com/rocallahan/svg-opentype-workshop/settings) and set “default branch” to “gh-pages”, and
2. go to the [branches](https://github.com/rocallahan/svg-opentype-workshop/branches) and delete it, finally
3. delete it locally by doing `git branch -d master`

**Comment by rocallahan** [comment]
Ah, great, thanks!
