### ISSUE TITLE
Can you please set up a live demo of this?

### ISSUE THREAD

**Issue by behdad** [rocallahan/svg-opentype-workshop#6]
I remember it was online, but cannot find anymore.  Can you please set it up on github.io or something?  Thanks.

**Comment by miguelsousa** [comment]
@behdad This? http://rocallahan.github.io/svg-opentype-workshop/

**Comment by miguelsousa** [comment]
Issue #5 addressed this, I believe.

**Comment by behdad** [comment]
Right.  Thanks.  I _knew_ it's somewhere.  It's not easy to find via Google though.  Perhaps it can be linked from README.md?
